server {
  listen 80;
  absolute_redirect off;

  location = /index.html {
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    gzip_static on;
  }

  location /assets/ {
    alias /usr/share/nginx/html/assets/;
    include /etc/nginx/mime.types;

    add_header Cache-Control "public, max-age=31536000, immutable" always;

    gzip_static on;
  }

  location / {
    alias /usr/share/nginx/html/;
    include /etc/nginx/mime.types;

    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    gzip_static on;

    try_files $uri $uri/ /index.html;
  }
}
